name: my-model-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pydantic
  - lume-model=1.4 
  - numpy
  - prefect[viz]<2.0
  - pip 
  - pip: 
    - git+https://github.com/jacquelinegarrahan/lume-services.git

  # dev
  - pre-commit
  - pytest
  - pytest-cov
  - jupyterlab
