name: my-model-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pydantic
  - lume-model=1.4 
  - numpy
  - prefect[viz]<2.0
  - pip 
  - pip: 
    - https://github.com/jacquelinegarrahan/lume-services/releases/download/v0.0.4/lume-services-0.0.4.tar.gz

  # dev
  - pre-commit
  - pytest
  - pytest-cov
  - jupyterlab
