name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@main
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: my-model-dev
          environment-file: dev-environment.yml
          python-version: ${{ matrix.python-version }} # patch
      

      - name: Install 
        shell: bash -l {0}
        run: |
          pip install -e .

      - run: mkdir coverage

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --cov-report term --cov=my_model --junitxml=./coverage/pytest.xml | tee ./coverage/pytest-coverage.txt

      - name: store coverage files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage